#include "testutils.h"
#include "gmock/gmock.h"
#include "gtest/gtest.h"
#include <filesystem>
#include <iostream>
#include <string>

extern "C"
{
#include "test_interface.h"
#include "to_string.h"
#include <ccngen/action_handling.h>
}

class OptimizationTest : public testing::Test
{
  public:
    char *root_string = nullptr;
    char *symbols_string = nullptr;
    node_st *root = nullptr;
    std::string input_filepath;
    std::string err_output;
    std::string std_output;

    enum class Opt
    {
        ALL,
        ALGEBRAICSIMPLIFICATION,
        CONSTANTFOLDING,
        DEADCODEELIMINATION,
    };

  protected:
    OptimizationTest()
    {
    }

    void SetUpNoExecute(std::string filepath)
    {
        input_filepath =
            std::filesystem::absolute(std::string(PROJECT_DIRECTORY) + "/test/data/" + filepath);
        ASSERT_TRUE(std::filesystem::exists(input_filepath))
            << "File does not exist at path '" << input_filepath << "'";
    }

    void SetUpOpt(std::string filepath, Opt opt)
    {
        SetUpNoExecute(filepath);
        testing::internal::CaptureStdout();
        testing::internal::CaptureStderr();
        enum ccn_action_id mapped = convert(opt);
        if (mapped == CCNAC_ID_NULL)
        {
            FAIL() << "Failed to map the given 'Opt'";
        }
        root = run_optimization(input_filepath.c_str(), mapped);
        EXPECT_NE(nullptr, root) << "Could not parse ast in file: '" << input_filepath << "'";
        err_output = testing::internal::GetCapturedStderr();
        std_output = testing::internal::GetCapturedStdout();
        ASSERT_THAT(err_output,
                    testing::Not(testing::HasSubstr("error: Inconsistent node found in AST")));
        root_string = node_to_string(root);
        symbols_string = symbols_to_string(root);
    }

    void SetUp(std::string filepath)
    {
        SetUpOpt(filepath, Opt::ALL);
    }

    enum ccn_action_id convert(Opt opt)
    {
        switch (opt)
        {
        case Opt::ALL:
            return CCNAC_ID_OPTIMIZATION;
        case Opt::ALGEBRAICSIMPLIFICATION:
            return CCNAC_ID_ALGEBRAICSIMPLIFICATION;
        case Opt::CONSTANTFOLDING:
            return CCNAC_ID_CONSTANTFOLDING;
        case Opt::DEADCODEELIMINATION:
            return CCNAC_ID_DEADCODEELIMINATION;
        }

        return CCNAC_ID_NULL;
    }

    void TearDown() override
    {
        if (root_string != nullptr)
        {

            if (HasFailure())
            {
                std::cerr
                    << "========================================================================\n"
                    << "                        Node Representation\n"
                    << "========================================================================\n"
                    << root_string << std::endl;
            }

            free(root_string);
        }

        if (symbols_string != nullptr)
        {
            if (HasFailure())
            {
                std::cerr
                    << "========================================================================\n"
                    << "                        Symbol Tables of AST\n"
                    << "========================================================================\n"
                    << symbols_string << std::endl;
            }

            free(symbols_string);
        }

        if (root != nullptr)
        {
            cleanup_nodes(root);
            root = nullptr;
        }
    }
};

TEST_F(OptimizationTest, AlgebraicSimplifications)
{
    SetUpOpt("optimization/algebraic_simplification/main.cvc", Opt::ALGEBRAICSIMPLIFICATION);
    ASSERT_NE(nullptr, root);

    const char *expected = "Program\n"
                           "┢─ Declarations\n"
                           "┃  └─ GlobalDef -- has_export:'0'\n"
                           "┃     └─ VarDec -- type:'int'\n"
                           "┃        ├─ Var -- name:'@0_a'\n"
                           "┃        └─ NULL\n"
                           "┣─ Declarations\n"
                           "┃  └─ FunDec\n"
                           "┃     └─ FunHeader -- type:'void'\n"
                           "┃        ├─ Var -- name:'@fun_printInt'\n"
                           "┃        ┢─ Params -- type:'int'\n"
                           "┃        ┃  └─ Var -- name:'@0_val'\n"
                           "┃        ┗─ NULL\n"
                           "┣─ Declarations\n"
                           "┃  └─ FunDef -- has_export:'1'\n"
                           "┃     ├─ FunHeader -- type:'int'\n"
                           "┃     │  ├─ Var -- name:'@fun_main'\n"
                           "┃     │  └─ NULL\n"
                           "┃     └─ FunBody\n"
                           "┃        ┢─ VarDecs\n"
                           "┃        ┃  └─ VarDec -- type:'bool'\n"
                           "┃        ┃     ├─ Var -- name:'@1_bo3'\n"
                           "┃        ┃     └─ NULL\n"
                           "┃        ┣─ VarDecs\n"
                           "┃        ┃  └─ VarDec -- type:'bool'\n"
                           "┃        ┃     ├─ Var -- name:'@1_bo4'\n"
                           "┃        ┃     └─ NULL\n"
                           "┃        ┣─ VarDecs\n"
                           "┃        ┃  └─ VarDec -- type:'bool'\n"
                           "┃        ┃     ├─ Var -- name:'@1_bo5'\n"
                           "┃        ┃     └─ NULL\n"
                           "┃        ┣─ VarDecs\n"
                           "┃        ┃  └─ VarDec -- type:'bool'\n"
                           "┃        ┃     ├─ Var -- name:'@1_bo6'\n"
                           "┃        ┃     └─ NULL\n"
                           "┃        ┣─ VarDecs\n"
                           "┃        ┃  └─ VarDec -- type:'int'\n"
                           "┃        ┃     ├─ Var -- name:'@1_a'\n"
                           "┃        ┃     └─ NULL\n"
                           "┃        ┣─ VarDecs\n"
                           "┃        ┃  └─ VarDec -- type:'int'\n"
                           "┃        ┃     ├─ Var -- name:'@1_b'\n"
                           "┃        ┃     └─ NULL\n"
                           "┃        ┣─ VarDecs\n"
                           "┃        ┃  └─ VarDec -- type:'int'\n"
                           "┃        ┃     ├─ Var -- name:'@1_c'\n"
                           "┃        ┃     └─ NULL\n"
                           "┃        ┣─ VarDecs\n"
                           "┃        ┃  └─ VarDec -- type:'int'\n"
                           "┃        ┃     ├─ Var -- name:'@1_d'\n"
                           "┃        ┃     └─ NULL\n"
                           "┃        ┣─ VarDecs\n"
                           "┃        ┃  └─ VarDec -- type:'int'\n"
                           "┃        ┃     ├─ Var -- name:'@1_e'\n"
                           "┃        ┃     └─ NULL\n"
                           "┃        ┣─ VarDecs\n"
                           "┃        ┃  └─ VarDec -- type:'int'\n"
                           "┃        ┃     ├─ Var -- name:'@1_f'\n"
                           "┃        ┃     └─ NULL\n"
                           "┃        ┣─ VarDecs\n"
                           "┃        ┃  └─ VarDec -- type:'int'\n"
                           "┃        ┃     ├─ Var -- name:'@1_a3'\n"
                           "┃        ┃     └─ NULL\n"
                           "┃        ┣─ VarDecs\n"
                           "┃        ┃  └─ VarDec -- type:'int'\n"
                           "┃        ┃     ├─ Var -- name:'@1_a4'\n"
                           "┃        ┃     └─ NULL\n"
                           "┃        ┣─ VarDecs\n"
                           "┃        ┃  └─ VarDec -- type:'int'\n"
                           "┃        ┃     ├─ Var -- name:'@1_a5'\n"
                           "┃        ┃     └─ NULL\n"
                           "┃        ┣─ VarDecs\n"
                           "┃        ┃  └─ VarDec -- type:'int'\n"
                           "┃        ┃     ├─ Var -- name:'@1_a6'\n"
                           "┃        ┃     └─ NULL\n"
                           "┃        ┣─ VarDecs\n"
                           "┃        ┃  └─ VarDec -- type:'float'\n"
                           "┃        ┃     ├─ Var -- name:'@1_g1'\n"
                           "┃        ┃     └─ NULL\n"
                           "┃        ┣─ VarDecs\n"
                           "┃        ┃  └─ VarDec -- type:'float'\n"
                           "┃        ┃     ├─ Var -- name:'@1_g2'\n"
                           "┃        ┃     └─ NULL\n"
                           "┃        ┣─ VarDecs\n"
                           "┃        ┃  └─ VarDec -- type:'float'\n"
                           "┃        ┃     ├─ Var -- name:'@1_g5'\n"
                           "┃        ┃     └─ NULL\n"
                           "┃        ┣─ VarDecs\n"
                           "┃        ┃  └─ VarDec -- type:'float'\n"
                           "┃        ┃     ├─ Var -- name:'@1_g6'\n"
                           "┃        ┃     └─ NULL\n"
                           "┃        ┣─ VarDecs\n"
                           "┃        ┃  └─ VarDec -- type:'float'\n"
                           "┃        ┃     ├─ Var -- name:'@1_h1'\n"
                           "┃        ┃     └─ NULL\n"
                           "┃        ┣─ VarDecs\n"
                           "┃        ┃  └─ VarDec -- type:'float'\n"
                           "┃        ┃     ├─ Var -- name:'@1_h2'\n"
                           "┃        ┃     └─ NULL\n"
                           "┃        ┣─ VarDecs\n"
                           "┃        ┃  └─ VarDec -- type:'float'\n"
                           "┃        ┃     ├─ Var -- name:'@1_i'\n"
                           "┃        ┃     └─ NULL\n"
                           "┃        ┣─ VarDecs\n"
                           "┃        ┃  └─ VarDec -- type:'bool'\n"
                           "┃        ┃     ├─ Var -- name:'@1_j'\n"
                           "┃        ┃     └─ NULL\n"
                           "┃        ┣─ VarDecs\n"
                           "┃        ┃  └─ VarDec -- type:'int'\n"
                           "┃        ┃     ├─ Var -- name:'@1_mi1'\n"
                           "┃        ┃     └─ NULL\n"
                           "┃        ┣─ VarDecs\n"
                           "┃        ┃  └─ VarDec -- type:'int'\n"
                           "┃        ┃     ├─ Var -- name:'@1_mi2'\n"
                           "┃        ┃     └─ NULL\n"
                           "┃        ┣─ VarDecs\n"
                           "┃        ┃  └─ VarDec -- type:'float'\n"
                           "┃        ┃     ├─ Var -- name:'@1_mf1'\n"
                           "┃        ┃     └─ NULL\n"
                           "┃        ┣─ VarDecs\n"
                           "┃        ┃  └─ VarDec -- type:'float'\n"
                           "┃        ┃     ├─ Var -- name:'@1_mf2'\n"
                           "┃        ┃     └─ NULL\n"
                           "┃        ┣─ VarDecs\n"
                           "┃        ┃  └─ VarDec -- type:'bool'\n"
                           "┃        ┃     ├─ Var -- name:'@1_mb1'\n"
                           "┃        ┃     └─ NULL\n"
                           "┃        ┣─ VarDecs\n"
                           "┃        ┃  └─ VarDec -- type:'bool'\n"
                           "┃        ┃     ├─ Var -- name:'@1_mb2'\n"
                           "┃        ┃     └─ NULL\n"
                           "┃        ┡─ NULL\n"
                           "┃        ├─ NULL\n"
                           "┃        ┢─ Statements\n"
                           "┃        ┃  └─ Assign\n"
                           "┃        ┃     ├─ Var -- name:'@1_a'\n"
                           "┃        ┃     └─ Int -- val:'-3'\n"
                           "┃        ┣─ Statements\n"
                           "┃        ┃  └─ Assign\n"
                           "┃        ┃     ├─ Var -- name:'@1_b'\n"
                           "┃        ┃     └─ Int -- val:'-2'\n"
                           "┃        ┣─ Statements\n"
                           "┃        ┃  └─ Assign\n"
                           "┃        ┃     ├─ Var -- name:'@1_c'\n"
                           "┃        ┃     └─ Int -- val:'-1'\n"
                           "┃        ┣─ Statements\n"
                           "┃        ┃  └─ Assign\n"
                           "┃        ┃     ├─ Var -- name:'@1_d'\n"
                           "┃        ┃     └─ Int -- val:'1'\n"
                           "┃        ┣─ Statements\n"
                           "┃        ┃  └─ Assign\n"
                           "┃        ┃     ├─ Var -- name:'@1_e'\n"
                           "┃        ┃     └─ Int -- val:'2'\n"
                           "┃        ┣─ Statements\n"
                           "┃        ┃  └─ Assign\n"
                           "┃        ┃     ├─ Var -- name:'@1_f'\n"
                           "┃        ┃     └─ Int -- val:'3'\n"
                           "┃        ┣─ Statements\n"
                           "┃        ┃  └─ Assign\n"
                           "┃        ┃     ├─ Var -- name:'@1_a3'\n"
                           "┃        ┃     └─ Int -- val:'0'\n"
                           "┃        ┣─ Statements\n"
                           "┃        ┃  └─ Assign\n"
                           "┃        ┃     ├─ Var -- name:'@1_a4'\n"
                           "┃        ┃     └─ Int -- val:'0'\n"
                           "┃        ┣─ Statements\n"
                           "┃        ┃  └─ Assign\n"
                           "┃        ┃     ├─ Var -- name:'@1_a5'\n"
                           "┃        ┃     └─ Int -- val:'0'\n"
                           "┃        ┣─ Statements\n"
                           "┃        ┃  └─ Assign\n"
                           "┃        ┃     ├─ Var -- name:'@1_a6'\n"
                           "┃        ┃     └─ Int -- val:'0'\n"
                           "┃        ┣─ Statements\n"
                           "┃        ┃  └─ Assign\n"
                           "┃        ┃     ├─ Var -- name:'@1_g1'\n"
                           "┃        ┃     └─ Float -- val:'4.200000'\n"
                           "┃        ┣─ Statements\n"
                           "┃        ┃  └─ Assign\n"
                           "┃        ┃     ├─ Var -- name:'@1_g2'\n"
                           "┃        ┃     └─ Float -- val:'3.100000'\n"
                           "┃        ┣─ Statements\n"
                           "┃        ┃  └─ Assign\n"
                           "┃        ┃     ├─ Var -- name:'@1_g5'\n"
                           "┃        ┃     └─ Float -- val:'1.200000'\n"
                           "┃        ┣─ Statements\n"
                           "┃        ┃  └─ Assign\n"
                           "┃        ┃     ├─ Var -- name:'@1_g6'\n"
                           "┃        ┃     └─ Float -- val:'31.200000'\n"
                           "┃        ┣─ Statements\n"
                           "┃        ┃  └─ Assign\n"
                           "┃        ┃     ├─ Var -- name:'@1_h1'\n"
                           "┃        ┃     └─ Float -- val:'2.000000'\n"
                           "┃        ┣─ Statements\n"
                           "┃        ┃  └─ Assign\n"
                           "┃        ┃     ├─ Var -- name:'@1_h2'\n"
                           "┃        ┃     └─ Float -- val:'1.000000'\n"
                           "┃        ┣─ Statements\n"
                           "┃        ┃  └─ Assign\n"
                           "┃        ┃     ├─ Var -- name:'@1_i'\n"
                           "┃        ┃     └─ Float -- val:'0.000000'\n"
                           "┃        ┣─ Statements\n"
                           "┃        ┃  └─ Assign\n"
                           "┃        ┃     ├─ Var -- name:'@1_j'\n"
                           "┃        ┃     └─ Bool -- val:'1'\n"
                           "┃        ┣─ Statements\n"
                           "┃        ┃  └─ Assign\n"
                           "┃        ┃     ├─ Var -- name:'@1_mi1'\n"
                           "┃        ┃     └─ Var -- name:'@1_a'\n"
                           "┃        ┣─ Statements\n"
                           "┃        ┃  └─ Assign\n"
                           "┃        ┃     ├─ Var -- name:'@1_mi2'\n"
                           "┃        ┃     └─ Int -- val:'-1'\n"
                           "┃        ┣─ Statements\n"
                           "┃        ┃  └─ Assign\n"
                           "┃        ┃     ├─ Var -- name:'@1_mf1'\n"
                           "┃        ┃     └─ Monop -- op:'-'\n"
                           "┃        ┃        └─ Var -- name:'@1_g1'\n"
                           "┃        ┣─ Statements\n"
                           "┃        ┃  └─ Assign\n"
                           "┃        ┃     ├─ Var -- name:'@1_mf2'\n"
                           "┃        ┃     └─ Float -- val:'1.000000'\n"
                           "┃        ┣─ Statements\n"
                           "┃        ┃  └─ Assign\n"
                           "┃        ┃     ├─ Var -- name:'@1_mb1'\n"
                           "┃        ┃     └─ Monop -- op:'!'\n"
                           "┃        ┃        └─ Var -- name:'@1_j'\n"
                           "┃        ┣─ Statements\n"
                           "┃        ┃  └─ Assign\n"
                           "┃        ┃     ├─ Var -- name:'@1_mb2'\n"
                           "┃        ┃     └─ Bool -- val:'0'\n"
                           "┃        ┣─ Statements\n"
                           "┃        ┃  └─ Assign\n"
                           "┃        ┃     ├─ Var -- name:'@1_a'\n"
                           "┃        ┃     └─ Var -- name:'@1_a'\n"
                           "┃        ┣─ Statements\n"
                           "┃        ┃  └─ Assign\n"
                           "┃        ┃     ├─ Var -- name:'@1_b'\n"
                           "┃        ┃     └─ Int -- val:'0'\n"
                           "┃        ┣─ Statements\n"
                           "┃        ┃  └─ Assign\n"
                           "┃        ┃     ├─ Var -- name:'@1_a3'\n"
                           "┃        ┃     └─ Int -- val:'5'\n"
                           "┃        ┣─ Statements\n"
                           "┃        ┃  └─ Assign\n"
                           "┃        ┃     ├─ Var -- name:'@1_a4'\n"
                           "┃        ┃     └─ Int -- val:'5'\n"
                           "┃        ┣─ Statements\n"
                           "┃        ┃  └─ Assign\n"
                           "┃        ┃     ├─ Var -- name:'@1_a5'\n"
                           "┃        ┃     └─ Binop -- op:'+'\n"
                           "┃        ┃        ├─ Int -- val:'5'\n"
                           "┃        ┃        └─ Int -- val:'5'\n"
                           "┃        ┣─ Statements\n"
                           "┃        ┃  └─ Assign\n"
                           "┃        ┃     ├─ Var -- name:'@1_a6'\n"
                           "┃        ┃     └─ Int -- val:'0'\n"
                           "┃        ┣─ Statements\n"
                           "┃        ┃  └─ Assign\n"
                           "┃        ┃     ├─ Var -- name:'@1_a3'\n"
                           "┃        ┃     └─ Int -- val:'5'\n"
                           "┃        ┣─ Statements\n"
                           "┃        ┃  └─ Assign\n"
                           "┃        ┃     ├─ Var -- name:'@1_a4'\n"
                           "┃        ┃     └─ Int -- val:'5'\n"
                           "┃        ┣─ Statements\n"
                           "┃        ┃  └─ Assign\n"
                           "┃        ┃     ├─ Var -- name:'@1_a5'\n"
                           "┃        ┃     └─ Binop -- op:'-'\n"
                           "┃        ┃        ├─ Int -- val:'5'\n"
                           "┃        ┃        └─ Int -- val:'5'\n"
                           "┃        ┣─ Statements\n"
                           "┃        ┃  └─ Assign\n"
                           "┃        ┃     ├─ Var -- name:'@1_a6'\n"
                           "┃        ┃     └─ Int -- val:'0'\n"
                           "┃        ┣─ Statements\n"
                           "┃        ┃  └─ Assign\n"
                           "┃        ┃     ├─ Var -- name:'@1_c'\n"
                           "┃        ┃     └─ Int -- val:'0'\n"
                           "┃        ┣─ Statements\n"
                           "┃        ┃  └─ Assign\n"
                           "┃        ┃     ├─ Var -- name:'@1_d'\n"
                           "┃        ┃     └─ Binop -- op:'+'\n"
                           "┃        ┃        ├─ Binop -- op:'*'\n"
                           "┃        ┃        │  ├─ Int -- val:'2'\n"
                           "┃        ┃        │  └─ Int -- val:'5'\n"
                           "┃        ┃        └─ Int -- val:'4'\n"
                           "┃        ┣─ Statements\n"
                           "┃        ┃  └─ Assign\n"
                           "┃        ┃     ├─ Var -- name:'@1_e'\n"
                           "┃        ┃     └─ Int -- val:'4'\n"
                           "┃        ┣─ Statements\n"
                           "┃        ┃  └─ Assign\n"
                           "┃        ┃     ├─ Var -- name:'@1_f'\n"
                           "┃        ┃     └─ Var -- name:'@1_e'\n"
                           "┃        ┣─ Statements\n"
                           "┃        ┃  └─ Assign\n"
                           "┃        ┃     ├─ Var -- name:'@1_c'\n"
                           "┃        ┃     └─ Binop -- op:'+'\n"
                           "┃        ┃        ├─ Binop -- op:'*'\n"
                           "┃        ┃        │  ├─ ProcCall\n"
                           "┃        ┃        │  │  ├─ Var -- name:'@fun_int_sideeffect'\n"
                           "┃        ┃        │  │  └─ NULL\n"
                           "┃        ┃        │  └─ Int -- val:'0'\n"
                           "┃        ┃        └─ Binop -- op:'*'\n"
                           "┃        ┃           ├─ Binop -- op:'+'\n"
                           "┃        ┃           │  ├─ ProcCall\n"
                           "┃        ┃           │  │  ├─ Var -- name:'@fun_int_sideeffect'\n"
                           "┃        ┃           │  │  └─ NULL\n"
                           "┃        ┃           │  └─ ProcCall\n"
                           "┃        ┃           │     ├─ Var -- name:'@fun_int_sideeffect'\n"
                           "┃        ┃           │     └─ NULL\n"
                           "┃        ┃           └─ Int -- val:'0'\n"
                           "┃        ┣─ Statements\n"
                           "┃        ┃  └─ Assign\n"
                           "┃        ┃     ├─ Var -- name:'@1_bo3'\n"
                           "┃        ┃     └─ Bool -- val:'0'\n"
                           "┃        ┣─ Statements\n"
                           "┃        ┃  └─ Assign\n"
                           "┃        ┃     ├─ Var -- name:'@1_bo4'\n"
                           "┃        ┃     └─ Bool -- val:'0'\n"
                           "┃        ┣─ Statements\n"
                           "┃        ┃  └─ Assign\n"
                           "┃        ┃     ├─ Var -- name:'@1_bo5'\n"
                           "┃        ┃     └─ Bool -- val:'1'\n"
                           "┃        ┣─ Statements\n"
                           "┃        ┃  └─ Assign\n"
                           "┃        ┃     ├─ Var -- name:'@1_bo6'\n"
                           "┃        ┃     └─ Bool -- val:'0'\n"
                           "┃        ┣─ Statements\n"
                           "┃        ┃  └─ Assign\n"
                           "┃        ┃     ├─ Var -- name:'@1_bo6'\n"
                           "┃        ┃     └─ Binop -- op:'*'\n"
                           "┃        ┃        ├─ Binop -- op:'*'\n"
                           "┃        ┃        │  ├─ ProcCall\n"
                           "┃        ┃        │  │  ├─ Var -- name:'@fun_bool_sideeffect'\n"
                           "┃        ┃        │  │  └─ NULL\n"
                           "┃        ┃        │  └─ Bool -- val:'0'\n"
                           "┃        ┃        └─ Binop -- op:'*'\n"
                           "┃        ┃           ├─ Pop -- type:'int'; replace_before_pop: '1'\n"
                           "┃        ┃           │  ├─ ProcCall\n"
                           "┃        ┃           │  │  ├─ Var -- name:'@fun_int_sideeffect'\n"
                           "┃        ┃           │  │  └─ NULL\n"
                           "┃        ┃           │  └─ Pop -- type:'int'; replace_before_pop: '1'\n"
                           "┃        ┃           │     ├─ ProcCall\n"
                           "┃        ┃           │     │  ├─ Var -- name:'@fun_int_sideeffect'\n"
                           "┃        ┃           │     │  └─ NULL\n"
                           "┃        ┃           │     └─ Bool -- val:'0'\n"
                           "┃        ┃           └─ Bool -- val:'0'\n"
                           "┃        ┣─ Statements\n"
                           "┃        ┃  └─ Assign\n"
                           "┃        ┃     ├─ Var -- name:'@1_bo3'\n"
                           "┃        ┃     └─ Bool -- val:'1'\n"
                           "┃        ┣─ Statements\n"
                           "┃        ┃  └─ Assign\n"
                           "┃        ┃     ├─ Var -- name:'@1_bo4'\n"
                           "┃        ┃     └─ Bool -- val:'1'\n"
                           "┃        ┣─ Statements\n"
                           "┃        ┃  └─ Assign\n"
                           "┃        ┃     ├─ Var -- name:'@1_bo5'\n"
                           "┃        ┃     └─ Bool -- val:'1'\n"
                           "┃        ┣─ Statements\n"
                           "┃        ┃  └─ Assign\n"
                           "┃        ┃     ├─ Var -- name:'@1_bo6'\n"
                           "┃        ┃     └─ Binop -- op:'+'\n"
                           "┃        ┃        ├─ Bool -- val:'0'\n"
                           "┃        ┃        └─ Bool -- val:'0'\n"
                           "┃        ┣─ Statements\n"
                           "┃        ┃  └─ Assign\n"
                           "┃        ┃     ├─ Var -- name:'@1_bo6'\n"
                           "┃        ┃     └─ Binop -- op:'+'\n"
                           "┃        ┃        ├─ Binop -- op:'+'\n"
                           "┃        ┃        │  ├─ ProcCall\n"
                           "┃        ┃        │  │  ├─ Var -- name:'@fun_bool_sideeffect'\n"
                           "┃        ┃        │  │  └─ NULL\n"
                           "┃        ┃        │  └─ Bool -- val:'1'\n"
                           "┃        ┃        └─ Binop -- op:'+'\n"
                           "┃        ┃           ├─ Pop -- type:'int'; replace_before_pop: '1'\n"
                           "┃        ┃           │  ├─ ProcCall\n"
                           "┃        ┃           │  │  ├─ Var -- name:'@fun_int_sideeffect'\n"
                           "┃        ┃           │  │  └─ NULL\n"
                           "┃        ┃           │  └─ ProcCall\n"
                           "┃        ┃           │     ├─ Var -- name:'@fun_bool_sideeffect'\n"
                           "┃        ┃           │     └─ NULL\n"
                           "┃        ┃           └─ Bool -- val:'1'\n"
                           "┃        ┣─ Statements\n"
                           "┃        ┃  └─ Assign\n"
                           "┃        ┃     ├─ Var -- name:'@1_bo5'\n"
                           "┃        ┃     └─ Binop -- op:'+'\n"
                           "┃        ┃        ├─ Ternary\n"
                           "┃        ┃        │  ├─ Ternary\n"
                           "┃        ┃        │  │  ├─ Binop -- op:'+'\n"
                           "┃        ┃        │  │  │  ├─ ProcCall\n"
                           "┃        ┃        │  │  │  │  ├─ Var -- name:'@fun_bool_sideeffect'\n"
                           "┃        ┃        │  │  │  │  └─ NULL\n"
                           "┃        ┃        │  │  │  └─ Bool -- val:'1'\n"
                           "┃        ┃        │  │  ├─ ProcCall\n"
                           "┃        ┃        │  │  │  ├─ Var -- name:'@fun_bool_sideeffect'\n"
                           "┃        ┃        │  │  │  └─ NULL\n"
                           "┃        ┃        │  │  └─ Bool -- val:'0'\n"
                           "┃        ┃        │  ├─ Bool -- val:'0'\n"
                           "┃        ┃        │  └─ ProcCall\n"
                           "┃        ┃        │     ├─ Var -- name:'@fun_bool_sideeffect'\n"
                           "┃        ┃        │     └─ NULL\n"
                           "┃        ┃        └─ Bool -- val:'1'\n"
                           "┃        ┣─ Statements\n"
                           "┃        ┃  └─ Assign\n"
                           "┃        ┃     ├─ Var -- name:'@1_g1'\n"
                           "┃        ┃     └─ Float -- val:'0.000000'\n"
                           "┃        ┣─ Statements\n"
                           "┃        ┃  └─ Assign\n"
                           "┃        ┃     ├─ Var -- name:'@1_g2'\n"
                           "┃        ┃     └─ Float -- val:'0.000000'\n"
                           "┃        ┣─ Statements\n"
                           "┃        ┃  └─ Assign\n"
                           "┃        ┃     ├─ Var -- name:'@1_h1'\n"
                           "┃        ┃     └─ Var -- name:'@1_g1'\n"
                           "┃        ┣─ Statements\n"
                           "┃        ┃  └─ Assign\n"
                           "┃        ┃     ├─ Var -- name:'@1_h2'\n"
                           "┃        ┃     └─ Var -- name:'@1_g2'\n"
                           "┃        ┣─ Statements\n"
                           "┃        ┃  └─ Assign\n"
                           "┃        ┃     ├─ Var -- name:'@1_i'\n"
                           "┃        ┃     └─ Float -- val:'1.000000'\n"
                           "┃        ┣─ Statements\n"
                           "┃        ┃  └─ Assign\n"
                           "┃        ┃     ├─ Var -- name:'@1_i'\n"
                           "┃        ┃     └─ Binop -- op:'*'\n"
                           "┃        ┃        ├─ Binop -- op:'+'\n"
                           "┃        ┃        │  ├─ Binop -- op:'+'\n"
                           "┃        ┃        │  │  ├─ Binop -- op:'+'\n"
                           "┃        ┃        │  │  │  ├─ ProcCall\n"
                           "┃        ┃        │  │  │  │  ├─ Var -- name:'@fun_float_sideeffect'\n"
                           "┃        ┃        │  │  │  │  ┢─ Exprs\n"
                           "┃        ┃        │  │  │  │  ┃  └─ Int -- val:'1'\n"
                           "┃        ┃        │  │  │  │  ┗─ NULL\n"
                           "┃        ┃        │  │  │  └─ Cast -- type:'float'\n"
                           "┃        ┃        │  │  │     └─ ProcCall\n"
                           "┃        ┃        │  │  │        ├─ Var -- name:'@fun_int_sideeffect'\n"
                           "┃        ┃        │  │  │        └─ NULL\n"
                           "┃        ┃        │  │  └─ ProcCall\n"
                           "┃        ┃        │  │     ├─ Var -- name:'@fun_float_sideeffect'\n"
                           "┃        ┃        │  │     ┢─ Exprs\n"
                           "┃        ┃        │  │     ┃  └─ Int -- val:'2'\n"
                           "┃        ┃        │  │     ┗─ NULL\n"
                           "┃        ┃        │  └─ ProcCall\n"
                           "┃        ┃        │     ├─ Var -- name:'@fun_float_sideeffect'\n"
                           "┃        ┃        │     ┢─ Exprs\n"
                           "┃        ┃        │     ┃  └─ Int -- val:'3'\n"
                           "┃        ┃        │     ┗─ NULL\n"
                           "┃        ┃        └─ Float -- val:'0.000000'\n"
                           "┃        ┣─ Statements\n"
                           "┃        ┃  └─ Assign\n"
                           "┃        ┃     ├─ Var -- name:'@1_g1'\n"
                           "┃        ┃     └─ Binop -- op:'+'\n"
                           "┃        ┃        ├─ Float -- val:'1.000000'\n"
                           "┃        ┃        └─ Float -- val:'5.000000'\n"
                           "┃        ┣─ Statements\n"
                           "┃        ┃  └─ Assign\n"
                           "┃        ┃     ├─ Var -- name:'@1_g2'\n"
                           "┃        ┃     └─ Binop -- op:'+'\n"
                           "┃        ┃        ├─ Float -- val:'5.000000'\n"
                           "┃        ┃        └─ Float -- val:'1.000000'\n"
                           "┃        ┣─ Statements\n"
                           "┃        ┃  └─ Assign\n"
                           "┃        ┃     ├─ Var -- name:'@1_g5'\n"
                           "┃        ┃     └─ Binop -- op:'+'\n"
                           "┃        ┃        ├─ Float -- val:'1.000000'\n"
                           "┃        ┃        └─ Float -- val:'1.000000'\n"
                           "┃        ┣─ Statements\n"
                           "┃        ┃  └─ Assign\n"
                           "┃        ┃     ├─ Var -- name:'@1_g6'\n"
                           "┃        ┃     └─ Binop -- op:'+'\n"
                           "┃        ┃        ├─ Float -- val:'5.000000'\n"
                           "┃        ┃        └─ Float -- val:'5.000000'\n"
                           "┃        ┣─ Statements\n"
                           "┃        ┃  └─ Assign\n"
                           "┃        ┃     ├─ Var -- name:'@1_b'\n"
                           "┃        ┃     └─ Var -- name:'@1_b'\n"
                           "┃        ┣─ Statements\n"
                           "┃        ┃  └─ Assign\n"
                           "┃        ┃     ├─ Var -- name:'@1_b'\n"
                           "┃        ┃     └─ Var -- name:'@1_b'\n"
                           "┃        ┣─ Statements\n"
                           "┃        ┃  └─ Assign\n"
                           "┃        ┃     ├─ Var -- name:'@1_b'\n"
                           "┃        ┃     └─ Monop -- op:'-'\n"
                           "┃        ┃        └─ Var -- name:'@1_b'\n"
                           "┃        ┣─ Statements\n"
                           "┃        ┃  └─ Assign\n"
                           "┃        ┃     ├─ Var -- name:'@1_b'\n"
                           "┃        ┃     └─ Monop -- op:'-'\n"
                           "┃        ┃        └─ Var -- name:'@1_b'\n"
                           "┃        ┣─ Statements\n"
                           "┃        ┃  └─ Assign\n"
                           "┃        ┃     ├─ Var -- name:'@1_g5'\n"
                           "┃        ┃     └─ Var -- name:'@1_g5'\n"
                           "┃        ┣─ Statements\n"
                           "┃        ┃  └─ Assign\n"
                           "┃        ┃     ├─ Var -- name:'@1_g5'\n"
                           "┃        ┃     └─ Monop -- op:'-'\n"
                           "┃        ┃        └─ Var -- name:'@1_g5'\n"
                           "┃        ┣─ Statements\n"
                           "┃        ┃  └─ RetStatement\n"
                           "┃        ┃     └─ Int -- val:'0'\n"
                           "┃        ┗─ NULL\n"
                           "┣─ Declarations\n"
                           "┃  └─ FunDef -- has_export:'0'\n"
                           "┃     ├─ FunHeader -- type:'int'\n"
                           "┃     │  ├─ Var -- name:'@fun_int_sideeffect'\n"
                           "┃     │  └─ NULL\n"
                           "┃     └─ FunBody\n"
                           "┃        ├─ NULL\n"
                           "┃        ├─ NULL\n"
                           "┃        ┢─ Statements\n"
                           "┃        ┃  └─ Assign\n"
                           "┃        ┃     ├─ Var -- name:'@0_a'\n"
                           "┃        ┃     └─ Int -- val:'10'\n"
                           "┃        ┣─ Statements\n"
                           "┃        ┃  └─ RetStatement\n"
                           "┃        ┃     └─ Int -- val:'10'\n"
                           "┃        ┗─ NULL\n"
                           "┣─ Declarations\n"
                           "┃  └─ FunDef -- has_export:'0'\n"
                           "┃     ├─ FunHeader -- type:'float'\n"
                           "┃     │  ├─ Var -- name:'@fun_float_sideeffect'\n"
                           "┃     │  ┢─ Params -- type:'int'\n"
                           "┃     │  ┃  └─ Var -- name:'@1_i'\n"
                           "┃     │  ┗─ NULL\n"
                           "┃     └─ FunBody\n"
                           "┃        ├─ NULL\n"
                           "┃        ├─ NULL\n"
                           "┃        ┢─ Statements\n"
                           "┃        ┃  └─ Assign\n"
                           "┃        ┃     ├─ Var -- name:'@0_a'\n"
                           "┃        ┃     └─ Int -- val:'10'\n"
                           "┃        ┣─ Statements\n"
                           "┃        ┃  └─ RetStatement\n"
                           "┃        ┃     └─ Float -- val:'10.000000'\n"
                           "┃        ┗─ NULL\n"
                           "┣─ Declarations\n"
                           "┃  └─ FunDef -- has_export:'0'\n"
                           "┃     ├─ FunHeader -- type:'bool'\n"
                           "┃     │  ├─ Var -- name:'@fun_bool_sideeffect'\n"
                           "┃     │  └─ NULL\n"
                           "┃     └─ FunBody\n"
                           "┃        ├─ NULL\n"
                           "┃        ├─ NULL\n"
                           "┃        ┢─ Statements\n"
                           "┃        ┃  └─ ProcCall\n"
                           "┃        ┃     ├─ Var -- name:'@fun_printInt'\n"
                           "┃        ┃     ┢─ Exprs\n"
                           "┃        ┃     ┃  └─ Int -- val:'10'\n"
                           "┃        ┃     ┗─ NULL\n"
                           "┃        ┣─ Statements\n"
                           "┃        ┃  └─ RetStatement\n"
                           "┃        ┃     └─ Bool -- val:'1'\n"
                           "┃        ┗─ NULL\n"
                           "┣─ Declarations\n"
                           "┃  └─ FunDef -- has_export:'1'\n"
                           "┃     ├─ FunHeader -- type:'void'\n"
                           "┃     │  ├─ Var -- name:'__init'\n"
                           "┃     │  └─ NULL\n"
                           "┃     └─ FunBody\n"
                           "┃        ├─ NULL\n"
                           "┃        ├─ NULL\n"
                           "┃        ┢─ Statements\n"
                           "┃        ┃  └─ Assign\n"
                           "┃        ┃     ├─ Var -- name:'@0_a'\n"
                           "┃        ┃     └─ Int -- val:'5'\n"
                           "┃        ┗─ NULL\n"
                           "┗─ NULL\n";

    ASSERT_MLSTREQ(expected, root_string);

    expected =
        "┌─ 0: Program\n"
        "├─ __init: FunHeader -- type:'void' -- Params: (null)\n"
        "├─ @0_a: VarDec -- type:'int'\n"
        "├─ @fun_bool_sideeffect: FunHeader -- type:'bool' -- Params: (null)\n"
        "├─ @fun_printInt: FunHeader -- type:'void' -- Params: int (Var -- name:'@0_val')\n"
        "├─ @fun_int_sideeffect: FunHeader -- type:'int' -- Params: (null)\n"
        "├─ @fun_main: FunHeader -- type:'int' -- Params: (null)\n"
        "├─ @fun_float_sideeffect: FunHeader -- type:'float' -- Params: int (Var -- name:'@1_i')\n"
        "└────────────────────\n"
        "\n"
        "┌─ 1: FunDef '@fun_main' -- parent: '0: Program'\n"
        "├─ @1_mb1: VarDec -- type:'bool'\n"
        "├─ @1_mb2: VarDec -- type:'bool'\n"
        "├─ @1_g1: VarDec -- type:'float'\n"
        "├─ @1_g2: VarDec -- type:'float'\n"
        "├─ @1_g5: VarDec -- type:'float'\n"
        "├─ @1_g6: VarDec -- type:'float'\n"
        "├─ @1_h1: VarDec -- type:'float'\n"
        "├─ @1_h2: VarDec -- type:'float'\n"
        "├─ @1_mf1: VarDec -- type:'float'\n"
        "├─ @1_mf2: VarDec -- type:'float'\n"
        "├─ @1_a: VarDec -- type:'int'\n"
        "├─ @1_b: VarDec -- type:'int'\n"
        "├─ @1_c: VarDec -- type:'int'\n"
        "├─ @1_d: VarDec -- type:'int'\n"
        "├─ @1_e: VarDec -- type:'int'\n"
        "├─ @1_f: VarDec -- type:'int'\n"
        "├─ @1_i: VarDec -- type:'float'\n"
        "├─ @1_j: VarDec -- type:'bool'\n"
        "├─ @1_bo3: VarDec -- type:'bool'\n"
        "├─ @1_bo4: VarDec -- type:'bool'\n"
        "├─ @1_bo5: VarDec -- type:'bool'\n"
        "├─ @1_bo6: VarDec -- type:'bool'\n"
        "├─ @1_mi1: VarDec -- type:'int'\n"
        "├─ @1_mi2: VarDec -- type:'int'\n"
        "├─ @1_a3: VarDec -- type:'int'\n"
        "├─ @1_a4: VarDec -- type:'int'\n"
        "├─ @1_a5: VarDec -- type:'int'\n"
        "├─ @1_a6: VarDec -- type:'int'\n"
        "└────────────────────\n"
        "\n"
        "┌─ 1: FunDef '@fun_int_sideeffect' -- parent: '0: Program'\n"
        "└────────────────────\n"
        "\n"
        "┌─ 1: FunDef '@fun_float_sideeffect' -- parent: '0: Program'\n"
        "├─ @1_i: Params -- type:'int'\n"
        "└────────────────────\n"
        "\n"
        "┌─ 1: FunDef '@fun_bool_sideeffect' -- parent: '0: Program'\n"
        "└────────────────────\n"
        "\n"
        "┌─ 1: FunDef '__init' -- parent: '0: Program'\n"
        "└────────────────────\n";

    ASSERT_MLSTREQ(expected, symbols_string);
}

TEST_F(OptimizationTest, ConstantFolding)
{
    SetUpOpt("optimization/constant_folding/main.cvc", Opt::CONSTANTFOLDING);
    ASSERT_NE(nullptr, root);

    const char *expected = "Program\n"
                           "┢─ Declarations\n"
                           "┃  └─ FunDef -- has_export:'1'\n"
                           "┃     ├─ FunHeader -- type:'int'\n"
                           "┃     │  ├─ Var -- name:'@fun_main'\n"
                           "┃     │  └─ NULL\n"
                           "┃     └─ FunBody\n"
                           "┃        ┢─ VarDecs\n"
                           "┃        ┃  └─ VarDec -- type:'int'\n"
                           "┃        ┃     ├─ Var -- name:'@1_a'\n"
                           "┃        ┃     └─ NULL\n"
                           "┃        ┣─ VarDecs\n"
                           "┃        ┃  └─ VarDec -- type:'int'\n"
                           "┃        ┃     ├─ Var -- name:'@1_b'\n"
                           "┃        ┃     └─ NULL\n"
                           "┃        ┣─ VarDecs\n"
                           "┃        ┃  └─ VarDec -- type:'int'\n"
                           "┃        ┃     ├─ Var -- name:'@1_c'\n"
                           "┃        ┃     └─ NULL\n"
                           "┃        ┣─ VarDecs\n"
                           "┃        ┃  └─ VarDec -- type:'float'\n"
                           "┃        ┃     ├─ Var -- name:'@1_d'\n"
                           "┃        ┃     └─ NULL\n"
                           "┃        ┣─ VarDecs\n"
                           "┃        ┃  └─ VarDec -- type:'float'\n"
                           "┃        ┃     ├─ Var -- name:'@1_e'\n"
                           "┃        ┃     └─ NULL\n"
                           "┃        ┣─ VarDecs\n"
                           "┃        ┃  └─ VarDec -- type:'float'\n"
                           "┃        ┃     ├─ Var -- name:'@1_f'\n"
                           "┃        ┃     └─ NULL\n"
                           "┃        ┣─ VarDecs\n"
                           "┃        ┃  └─ VarDec -- type:'bool'\n"
                           "┃        ┃     ├─ Var -- name:'@1_g'\n"
                           "┃        ┃     └─ NULL\n"
                           "┃        ┣─ VarDecs\n"
                           "┃        ┃  └─ VarDec -- type:'bool'\n"
                           "┃        ┃     ├─ Var -- name:'@1_h'\n"
                           "┃        ┃     └─ NULL\n"
                           "┃        ┣─ VarDecs\n"
                           "┃        ┃  └─ VarDec -- type:'bool'\n"
                           "┃        ┃     ├─ Var -- name:'@1_i'\n"
                           "┃        ┃     └─ NULL\n"
                           "┃        ┡─ NULL\n"
                           "┃        ├─ NULL\n"
                           "┃        ┢─ Statements\n"
                           "┃        ┃  └─ Assign\n"
                           "┃        ┃     ├─ Var -- name:'@1_a'\n"
                           "┃        ┃     └─ Int -- val:'0'\n"
                           "┃        ┣─ Statements\n"
                           "┃        ┃  └─ Assign\n"
                           "┃        ┃     ├─ Var -- name:'@1_b'\n"
                           "┃        ┃     └─ Int -- val:'1'\n"
                           "┃        ┣─ Statements\n"
                           "┃        ┃  └─ Assign\n"
                           "┃        ┃     ├─ Var -- name:'@1_c'\n"
                           "┃        ┃     └─ Int -- val:'2'\n"
                           "┃        ┣─ Statements\n"
                           "┃        ┃  └─ Assign\n"
                           "┃        ┃     ├─ Var -- name:'@1_d'\n"
                           "┃        ┃     └─ Float -- val:'1.000000'\n"
                           "┃        ┣─ Statements\n"
                           "┃        ┃  └─ Assign\n"
                           "┃        ┃     ├─ Var -- name:'@1_e'\n"
                           "┃        ┃     └─ Float -- val:'2.000000'\n"
                           "┃        ┣─ Statements\n"
                           "┃        ┃  └─ Assign\n"
                           "┃        ┃     ├─ Var -- name:'@1_f'\n"
                           "┃        ┃     └─ Float -- val:'3.000000'\n"
                           "┃        ┣─ Statements\n"
                           "┃        ┃  └─ Assign\n"
                           "┃        ┃     ├─ Var -- name:'@1_g'\n"
                           "┃        ┃     └─ Bool -- val:'1'\n"
                           "┃        ┣─ Statements\n"
                           "┃        ┃  └─ Assign\n"
                           "┃        ┃     ├─ Var -- name:'@1_h'\n"
                           "┃        ┃     └─ Bool -- val:'0'\n"
                           "┃        ┣─ Statements\n"
                           "┃        ┃  └─ Assign\n"
                           "┃        ┃     ├─ Var -- name:'@1_i'\n"
                           "┃        ┃     └─ Bool -- val:'0'\n"
                           "┃        ┣─ Statements\n"
                           "┃        ┃  └─ Assign\n"
                           "┃        ┃     ├─ Var -- name:'@1_a'\n"
                           "┃        ┃     └─ Int -- val:'8'\n"
                           "┃        ┣─ Statements\n"
                           "┃        ┃  └─ Assign\n"
                           "┃        ┃     ├─ Var -- name:'@1_b'\n"
                           "┃        ┃     └─ Binop -- op:'+'\n"
                           "┃        ┃        ├─ Var -- name:'@1_a'\n"
                           "┃        ┃        └─ Int -- val:'3'\n"
                           "┃        ┣─ Statements\n"
                           "┃        ┃  └─ Assign\n"
                           "┃        ┃     ├─ Var -- name:'@1_c'\n"
                           "┃        ┃     └─ Binop -- op:'*'\n"
                           "┃        ┃        ├─ Binop -- op:'+'\n"
                           "┃        ┃        │  ├─ Binop -- op:'*'\n"
                           "┃        ┃        │  │  ├─ Var -- name:'@1_a'\n"
                           "┃        ┃        │  │  └─ Int -- val:'2'\n"
                           "┃        ┃        │  └─ Int -- val:'3'\n"
                           "┃        ┃        └─ Int -- val:'1'\n"
                           "┃        ┣─ Statements\n"
                           "┃        ┃  └─ Assign\n"
                           "┃        ┃     ├─ Var -- name:'@1_g'\n"
                           "┃        ┃     └─ Bool -- val:'1'\n"
                           "┃        ┣─ Statements\n"
                           "┃        ┃  └─ Assign\n"
                           "┃        ┃     ├─ Var -- name:'@1_d'\n"
                           "┃        ┃     └─ Float -- val:'-32.057724'\n"
                           "┃        ┣─ Statements\n"
                           "┃        ┃  └─ Assign\n"
                           "┃        ┃     ├─ Var -- name:'@1_e'\n"
                           "┃        ┃     └─ Binop -- op:'+'\n"
                           "┃        ┃        ├─ Binop -- op:'-'\n"
                           "┃        ┃        │  ├─ Float -- val:'4.400000'\n"
                           "┃        ┃        │  └─ Var -- name:'@1_e'\n"
                           "┃        ┃        └─ Float -- val:'3.000000'\n"
                           "┃        ┣─ Statements\n"
                           "┃        ┃  └─ Assign\n"
                           "┃        ┃     ├─ Var -- name:'@1_f'\n"
                           "┃        ┃     └─ Binop -- op:'*'\n"
                           "┃        ┃        ├─ Binop -- op:'+'\n"
                           "┃        ┃        │  ├─ Binop -- op:'*'\n"
                           "┃        ┃        │  │  ├─ Float -- val:'2.000000'\n"
                           "┃        ┃        │  │  └─ Var -- name:'@1_e'\n"
                           "┃        ┃        │  └─ Float -- val:'3.300000'\n"
                           "┃        ┃        └─ Float -- val:'5.600000'\n"
                           "┃        ┣─ Statements\n"
                           "┃        ┃  └─ Assign\n"
                           "┃        ┃     ├─ Var -- name:'@1_h'\n"
                           "┃        ┃     └─ Bool -- val:'1'\n"
                           "┃        ┣─ Statements\n"
                           "┃        ┃  └─ Assign\n"
                           "┃        ┃     ├─ Var -- name:'@1_i'\n"
                           "┃        ┃     └─ Bool -- val:'1'\n"
                           "┃        ┣─ Statements\n"
                           "┃        ┃  └─ RetStatement\n"
                           "┃        ┃     └─ Int -- val:'0'\n"
                           "┃        ┗─ NULL\n"
                           "┣─ Declarations\n"
                           "┃  └─ FunDef -- has_export:'1'\n"
                           "┃     ├─ FunHeader -- type:'void'\n"
                           "┃     │  ├─ Var -- name:'__init'\n"
                           "┃     │  └─ NULL\n"
                           "┃     └─ FunBody\n"
                           "┃        ├─ NULL\n"
                           "┃        ├─ NULL\n"
                           "┃        └─ NULL\n"
                           "┗─ NULL\n";

    ASSERT_MLSTREQ(expected, root_string);

    expected = "┌─ 0: Program\n"
               "├─ __init: FunHeader -- type:'void' -- Params: (null)\n"
               "├─ @fun_main: FunHeader -- type:'int' -- Params: (null)\n"
               "└────────────────────\n"
               "\n"
               "┌─ 1: FunDef '@fun_main' -- parent: '0: Program'\n"
               "├─ @1_a: VarDec -- type:'int'\n"
               "├─ @1_b: VarDec -- type:'int'\n"
               "├─ @1_c: VarDec -- type:'int'\n"
               "├─ @1_d: VarDec -- type:'float'\n"
               "├─ @1_e: VarDec -- type:'float'\n"
               "├─ @1_f: VarDec -- type:'float'\n"
               "├─ @1_g: VarDec -- type:'bool'\n"
               "├─ @1_h: VarDec -- type:'bool'\n"
               "├─ @1_i: VarDec -- type:'bool'\n"
               "└────────────────────\n"
               "\n"
               "┌─ 1: FunDef '__init' -- parent: '0: Program'\n"
               "└────────────────────\n";

    ASSERT_MLSTREQ(expected, symbols_string);
}

TEST_F(OptimizationTest, DeadCodeElimination)
{
    SetUpOpt("optimization/dead_code_elimination/main.cvc", Opt::DEADCODEELIMINATION);
    ASSERT_NE(nullptr, root);

    const char *expected = "Program\n"
                           "┢─ Declarations\n"
                           "┃  └─ GlobalDef -- has_export:'0'\n"
                           "┃     └─ VarDec -- type:'float'\n"
                           "┃        ├─ Var -- name:'@0_used_global'\n"
                           "┃        └─ NULL\n"
                           "┣─ Declarations\n"
                           "┃  └─ GlobalDef -- has_export:'0'\n"
                           "┃     └─ VarDec -- type:'int'\n"
                           "┃        ├─ Var -- name:'@0_i'\n"
                           "┃        └─ NULL\n"
                           "┣─ Declarations\n"
                           "┃  └─ GlobalDef -- has_export:'1'\n"
                           "┃     └─ VarDec -- type:'bool'\n"
                           "┃        ├─ Var -- name:'@0_unused_exported'\n"
                           "┃        └─ NULL\n"
                           "┣─ Declarations\n"
                           "┃  └─ FunDec\n"
                           "┃     └─ FunHeader -- type:'int'\n"
                           "┃        ├─ Var -- name:'@fun_extern_sideeffect'\n"
                           "┃        └─ NULL\n"
                           "┣─ Declarations\n"
                           "┃  └─ FunDec\n"
                           "┃     └─ FunHeader -- type:'int'\n"
                           "┃        ├─ Var -- name:'@fun_printInt'\n"
                           "┃        ┢─ Params -- type:'int'\n"
                           "┃        ┃  └─ Var -- name:'@0_val'\n"
                           "┃        ┗─ NULL\n"
                           "┣─ Declarations\n"
                           "┃  └─ FunDec\n"
                           "┃     └─ FunHeader -- type:'void'\n"
                           "┃        ├─ Var -- name:'@fun_printNewlines'\n"
                           "┃        ┢─ Params -- type:'int'\n"
                           "┃        ┃  └─ Var -- name:'@0_val'\n"
                           "┃        ┗─ NULL\n"
                           "┣─ Declarations\n"
                           "┃  └─ FunDef -- has_export:'1'\n"
                           "┃     ├─ FunHeader -- type:'int'\n"
                           "┃     │  ├─ Var -- name:'@fun_test'\n"
                           "┃     │  └─ NULL\n"
                           "┃     └─ FunBody\n"
                           "┃        ┢─ VarDecs\n"
                           "┃        ┃  └─ VarDec -- type:'int'\n"
                           "┃        ┃     ├─ Var -- name:'@1_a'\n"
                           "┃        ┃     └─ NULL\n"
                           "┃        ┡─ NULL\n"
                           "┃        ├─ NULL\n"
                           "┃        ┢─ Statements\n"
                           "┃        ┃  └─ Assign\n"
                           "┃        ┃     ├─ Var -- name:'@1_a'\n"
                           "┃        ┃     └─ ProcCall\n"
                           "┃        ┃        ├─ Var -- name:'@fun_no_sideeffect'\n"
                           "┃        ┃        └─ NULL\n"
                           "┃        ┣─ Statements\n"
                           "┃        ┃  └─ ProcCall\n"
                           "┃        ┃     ├─ Var -- name:'@fun_sideeffect'\n"
                           "┃        ┃     └─ NULL\n"
                           "┃        ┣─ Statements\n"
                           "┃        ┃  └─ RetStatement\n"
                           "┃        ┃     └─ Var -- name:'@1_a'\n"
                           "┃        ┗─ NULL\n"
                           "┣─ Declarations\n"
                           "┃  └─ FunDef -- has_export:'1'\n"
                           "┃     ├─ FunHeader -- type:'int'\n"
                           "┃     │  ├─ Var -- name:'@fun_main'\n"
                           "┃     │  └─ NULL\n"
                           "┃     └─ FunBody\n"
                           "┃        ┢─ VarDecs\n"
                           "┃        ┃  └─ VarDec -- type:'int'\n"
                           "┃        ┃     ├─ Var -- name:'@1_b'\n"
                           "┃        ┃     └─ NULL\n"
                           "┃        ┣─ VarDecs\n"
                           "┃        ┃  └─ VarDec -- type:'int'\n"
                           "┃        ┃     ├─ Var -- name:'@1_a'\n"
                           "┃        ┃     └─ NULL\n"
                           "┃        ┣─ VarDecs\n"
                           "┃        ┃  └─ VarDec -- type:'int'\n"
                           "┃        ┃     ├─ Var -- name:'@1_k'\n"
                           "┃        ┃     └─ NULL\n"
                           "┃        ┣─ VarDecs\n"
                           "┃        ┃  └─ VarDec -- type:'int'\n"
                           "┃        ┃     ├─ Var -- name:'@for3_i'\n"
                           "┃        ┃     └─ NULL\n"
                           "┃        ┡─ NULL\n"
                           "┃        ├─ NULL\n"
                           "┃        ┢─ Statements\n"
                           "┃        ┃  └─ Assign\n"
                           "┃        ┃     ├─ Var -- name:'@1_b'\n"
                           "┃        ┃     └─ Int -- val:'20'\n"
                           "┃        ┣─ Statements\n"
                           "┃        ┃  └─ ProcCall\n"
                           "┃        ┃     ├─ Var -- name:'@fun_test'\n"
                           "┃        ┃     └─ NULL\n"
                           "┃        ┣─ Statements\n"
                           "┃        ┃  └─ IfStatement\n"
                           "┃        ┃     ├─ Binop -- op:'=='\n"
                           "┃        ┃     │  ├─ Var -- name:'@1_b'\n"
                           "┃        ┃     │  └─ Int -- val:'20'\n"
                           "┃        ┃     ┢─ Statements\n"
                           "┃        ┃     ┃  └─ Assign\n"
                           "┃        ┃     ┃     ├─ Var -- name:'@1_a'\n"
                           "┃        ┃     ┃     └─ Int -- val:'10'\n"
                           "┃        ┃     ┡─ NULL\n"
                           "┃        ┃     ┢─ Statements\n"
                           "┃        ┃     ┃  └─ Assign\n"
                           "┃        ┃     ┃     ├─ Var -- name:'@1_a'\n"
                           "┃        ┃     ┃     └─ Int -- val:'20'\n"
                           "┃        ┃     ┣─ Statements\n"
                           "┃        ┃     ┃  └─ Assign\n"
                           "┃        ┃     ┃     ├─ Var -- name:'@1_a'\n"
                           "┃        ┃     ┃     └─ Binop -- op:'+'\n"
                           "┃        ┃     ┃        ├─ Var -- name:'@1_a'\n"
                           "┃        ┃     ┃        └─ Int -- val:'1'\n"
                           "┃        ┃     ┗─ NULL\n"
                           "┃        ┣─ Statements\n"
                           "┃        ┃  └─ ProcCall\n"
                           "┃        ┃     ├─ Var -- name:'@fun_printInt'\n"
                           "┃        ┃     ┢─ Exprs\n"
                           "┃        ┃     ┃  └─ Var -- name:'@1_a'\n"
                           "┃        ┃     ┗─ NULL\n"
                           "┃        ┣─ Statements\n"
                           "┃        ┃  └─ ProcCall\n"
                           "┃        ┃     ├─ Var -- name:'@fun_printNewlines'\n"
                           "┃        ┃     ┢─ Exprs\n"
                           "┃        ┃     ┃  └─ Int -- val:'2'\n"
                           "┃        ┃     ┗─ NULL\n"
                           "┃        ┣─ Statements\n"
                           "┃        ┃  └─ Assign\n"
                           "┃        ┃     ├─ Var -- name:'@1_a'\n"
                           "┃        ┃     └─ Int -- val:'20'\n"
                           "┃        ┣─ Statements\n"
                           "┃        ┃  └─ IfStatement\n"
                           "┃        ┃     ├─ Binop -- op:'=='\n"
                           "┃        ┃     │  ├─ Var -- name:'@1_b'\n"
                           "┃        ┃     │  └─ Int -- val:'20'\n"
                           "┃        ┃     ┢─ Statements\n"
                           "┃        ┃     ┃  └─ Assign\n"
                           "┃        ┃     ┃     ├─ Var -- name:'@1_a'\n"
                           "┃        ┃     ┃     └─ Int -- val:'10'\n"
                           "┃        ┃     ┡─ NULL\n"
                           "┃        ┃     └─ NULL\n"
                           "┃        ┣─ Statements\n"
                           "┃        ┃  └─ ProcCall\n"
                           "┃        ┃     ├─ Var -- name:'@fun_printInt'\n"
                           "┃        ┃     ┢─ Exprs\n"
                           "┃        ┃     ┃  └─ Var -- name:'@1_a'\n"
                           "┃        ┃     ┗─ NULL\n"
                           "┃        ┣─ Statements\n"
                           "┃        ┃  └─ ProcCall\n"
                           "┃        ┃     ├─ Var -- name:'@fun_printNewlines'\n"
                           "┃        ┃     ┢─ Exprs\n"
                           "┃        ┃     ┃  └─ Int -- val:'2'\n"
                           "┃        ┃     ┗─ NULL\n"
                           "┃        ┣─ Statements\n"
                           "┃        ┃  └─ Assign\n"
                           "┃        ┃     ├─ Var -- name:'@1_a'\n"
                           "┃        ┃     └─ Int -- val:'30'\n"
                           "┃        ┣─ Statements\n"
                           "┃        ┃  └─ IfStatement\n"
                           "┃        ┃     ├─ Binop -- op:'=='\n"
                           "┃        ┃     │  ├─ Var -- name:'@1_b'\n"
                           "┃        ┃     │  └─ Int -- val:'20'\n"
                           "┃        ┃     ├─ NULL\n"
                           "┃        ┃     ┢─ Statements\n"
                           "┃        ┃     ┃  └─ Assign\n"
                           "┃        ┃     ┃     ├─ Var -- name:'@1_a'\n"
                           "┃        ┃     ┃     └─ Int -- val:'10'\n"
                           "┃        ┃     ┗─ NULL\n"
                           "┃        ┣─ Statements\n"
                           "┃        ┃  └─ ProcCall\n"
                           "┃        ┃     ├─ Var -- name:'@fun_printInt'\n"
                           "┃        ┃     ┢─ Exprs\n"
                           "┃        ┃     ┃  └─ Var -- name:'@1_a'\n"
                           "┃        ┃     ┗─ NULL\n"
                           "┃        ┣─ Statements\n"
                           "┃        ┃  └─ IfStatement\n"
                           "┃        ┃     ├─ Ternary\n"
                           "┃        ┃     │  ├─ Ternary\n"
                           "┃        ┃     │  │  ├─ Binop -- op:'=='\n"
                           "┃        ┃     │  │  │  ├─ Var -- name:'@1_b'\n"
                           "┃        ┃     │  │  │  └─ ProcCall\n"
                           "┃        ┃     │  │  │     ├─ Var -- name:'@fun_no_sideeffect'\n"
                           "┃        ┃     │  │  │     └─ NULL\n"
                           "┃        ┃     │  │  ├─ Binop -- op:'=='\n"
                           "┃        ┃     │  │  │  ├─ Cast -- type:'float'\n"
                           "┃        ┃     │  │  │  │  └─ Var -- name:'@1_b'\n"
                           "┃        ┃     │  │  │  └─ ProcCall\n"
                           "┃        ┃     │  │  │     ├─ Var -- name:'@fun_sideeffect'\n"
                           "┃        ┃     │  │  │     └─ NULL\n"
                           "┃        ┃     │  │  └─ Bool -- val:'0'\n"
                           "┃        ┃     │  ├─ Binop -- op:'=='\n"
                           "┃        ┃     │  │  ├─ Cast -- type:'float'\n"
                           "┃        ┃     │  │  │  └─ Var -- name:'@1_b'\n"
                           "┃        ┃     │  │  └─ ProcCall\n"
                           "┃        ┃     │  │     ├─ Var -- name:'@fun_sideeffect'\n"
                           "┃        ┃     │  │     └─ NULL\n"
                           "┃        ┃     │  └─ Bool -- val:'0'\n"
                           "┃        ┃     ├─ NULL\n"
                           "┃        ┃     ┢─ Statements\n"
                           "┃        ┃     ┃  └─ ProcCall\n"
                           "┃        ┃     ┃     ├─ Var -- name:'@fun_sideeffect'\n"
                           "┃        ┃     ┃     └─ NULL\n"
                           "┃        ┃     ┗─ NULL\n"
                           "┃        ┣─ Statements\n"
                           "┃        ┃  └─ DoWhileLoop\n"
                           "┃        ┃     ├─ NULL\n"
                           "┃        ┃     └─ ProcCall\n"
                           "┃        ┃        ├─ Var -- name:'@fun_increase_sideeffect'\n"
                           "┃        ┃        ┢─ Exprs\n"
                           "┃        ┃        ┃  └─ Int -- val:'2'\n"
                           "┃        ┃        ┗─ NULL\n"
                           "┃        ┣─ Statements\n"
                           "┃        ┃  └─ ProcCall\n"
                           "┃        ┃     ├─ Var -- name:'@fun_printInt'\n"
                           "┃        ┃     ┢─ Exprs\n"
                           "┃        ┃     ┃  └─ Var -- name:'@0_i'\n"
                           "┃        ┃     ┗─ NULL\n"
                           "┃        ┣─ Statements\n"
                           "┃        ┃  └─ ProcCall\n"
                           "┃        ┃     ├─ Var -- name:'@fun_printNewlines'\n"
                           "┃        ┃     ┢─ Exprs\n"
                           "┃        ┃     ┃  └─ Int -- val:'2'\n"
                           "┃        ┃     ┗─ NULL\n"
                           "┃        ┣─ Statements\n"
                           "┃        ┃  └─ WhileLoop\n"
                           "┃        ┃     ├─ ProcCall\n"
                           "┃        ┃     │  ├─ Var -- name:'@fun_increase_sideeffect'\n"
                           "┃        ┃     │  ┢─ Exprs\n"
                           "┃        ┃     │  ┃  └─ Int -- val:'10'\n"
                           "┃        ┃     │  ┗─ NULL\n"
                           "┃        ┃     └─ NULL\n"
                           "┃        ┣─ Statements\n"
                           "┃        ┃  └─ ProcCall\n"
                           "┃        ┃     ├─ Var -- name:'@fun_printInt'\n"
                           "┃        ┃     ┢─ Exprs\n"
                           "┃        ┃     ┃  └─ Var -- name:'@0_i'\n"
                           "┃        ┃     ┗─ NULL\n"
                           "┃        ┣─ Statements\n"
                           "┃        ┃  └─ ProcCall\n"
                           "┃        ┃     ├─ Var -- name:'@fun_printNewlines'\n"
                           "┃        ┃     ┢─ Exprs\n"
                           "┃        ┃     ┃  └─ Int -- val:'2'\n"
                           "┃        ┃     ┗─ NULL\n"
                           "┃        ┣─ Statements\n"
                           "┃        ┃  └─ Assign\n"
                           "┃        ┃     ├─ Var -- name:'@1_k'\n"
                           "┃        ┃     └─ Int -- val:'20'\n"
                           "┃        ┣─ Statements\n"
                           "┃        ┃  └─ WhileLoop\n"
                           "┃        ┃     ├─ Binop -- op:'<'\n"
                           "┃        ┃     │  ├─ Var -- name:'@1_k'\n"
                           "┃        ┃     │  └─ Int -- val:'0'\n"
                           "┃        ┃     ┢─ Statements\n"
                           "┃        ┃     ┃  └─ Assign\n"
                           "┃        ┃     ┃     ├─ Var -- name:'@1_k'\n"
                           "┃        ┃     ┃     └─ Binop -- op:'+'\n"
                           "┃        ┃     ┃        ├─ Var -- name:'@1_k'\n"
                           "┃        ┃     ┃        └─ Int -- val:'1'\n"
                           "┃        ┃     ┗─ NULL\n"
                           "┃        ┣─ Statements\n"
                           "┃        ┃  └─ ProcCall\n"
                           "┃        ┃     ├─ Var -- name:'@fun_printInt'\n"
                           "┃        ┃     ┢─ Exprs\n"
                           "┃        ┃     ┃  └─ Var -- name:'@1_k'\n"
                           "┃        ┃     ┗─ NULL\n"
                           "┃        ┣─ Statements\n"
                           "┃        ┃  └─ ProcCall\n"
                           "┃        ┃     ├─ Var -- name:'@fun_printNewlines'\n"
                           "┃        ┃     ┢─ Exprs\n"
                           "┃        ┃     ┃  └─ Int -- val:'2'\n"
                           "┃        ┃     ┗─ NULL\n"
                           "┃        ┣─ Statements\n"
                           "┃        ┃  └─ DoWhileLoop\n"
                           "┃        ┃     ┢─ Statements\n"
                           "┃        ┃     ┃  └─ Assign\n"
                           "┃        ┃     ┃     ├─ Var -- name:'@1_k'\n"
                           "┃        ┃     ┃     └─ Binop -- op:'+'\n"
                           "┃        ┃     ┃        ├─ Var -- name:'@1_k'\n"
                           "┃        ┃     ┃        └─ Int -- val:'5'\n"
                           "┃        ┃     ┡─ NULL\n"
                           "┃        ┃     └─ Binop -- op:'<'\n"
                           "┃        ┃        ├─ Var -- name:'@1_k'\n"
                           "┃        ┃        └─ Int -- val:'0'\n"
                           "┃        ┣─ Statements\n"
                           "┃        ┃  └─ ProcCall\n"
                           "┃        ┃     ├─ Var -- name:'@fun_printInt'\n"
                           "┃        ┃     ┢─ Exprs\n"
                           "┃        ┃     ┃  └─ Var -- name:'@1_k'\n"
                           "┃        ┃     ┗─ NULL\n"
                           "┃        ┣─ Statements\n"
                           "┃        ┃  └─ ProcCall\n"
                           "┃        ┃     ├─ Var -- name:'@fun_printNewlines'\n"
                           "┃        ┃     ┢─ Exprs\n"
                           "┃        ┃     ┃  └─ Int -- val:'2'\n"
                           "┃        ┃     ┗─ NULL\n"
                           "┃        ┣─ Statements\n"
                           "┃        ┃  └─ ProcCall\n"
                           "┃        ┃     ├─ Var -- name:'@fun_sideeffect'\n"
                           "┃        ┃     └─ NULL\n"
                           "┃        ┣─ Statements\n"
                           "┃        ┃  └─ ProcCall\n"
                           "┃        ┃     ├─ Var -- name:'@fun_sideeffect'\n"
                           "┃        ┃     └─ NULL\n"
                           "┃        ┣─ Statements\n"
                           "┃        ┃  └─ ProcCall\n"
                           "┃        ┃     ├─ Var -- name:'@fun_increase_sideeffect'\n"
                           "┃        ┃     ┢─ Exprs\n"
                           "┃        ┃     ┃  └─ Int -- val:'5'\n"
                           "┃        ┃     ┗─ NULL\n"
                           "┃        ┣─ Statements\n"
                           "┃        ┃  └─ ForLoop\n"
                           "┃        ┃     ├─ Assign\n"
                           "┃        ┃     │  ├─ Var -- name:'@for3_i'\n"
                           "┃        ┃     │  └─ Int -- val:'1'\n"
                           "┃        ┃     ├─ Int -- val:'4'\n"
                           "┃        ┃     ├─ NULL\n"
                           "┃        ┃     ┢─ Statements\n"
                           "┃        ┃     ┃  └─ ProcCall\n"
                           "┃        ┃     ┃     ├─ Var -- name:'@fun_printInt'\n"
                           "┃        ┃     ┃     ┢─ Exprs\n"
                           "┃        ┃     ┃     ┃  └─ Var -- name:'@for3_i'\n"
                           "┃        ┃     ┃     ┗─ NULL\n"
                           "┃        ┃     ┗─ NULL\n"
                           "┃        ┣─ Statements\n"
                           "┃        ┃  └─ ProcCall\n"
                           "┃        ┃     ├─ Var -- name:'@fun_sideeffect'\n"
                           "┃        ┃     └─ NULL\n"
                           "┃        ┣─ Statements\n"
                           "┃        ┃  └─ IfStatement\n"
                           "┃        ┃     ├─ Ternary\n"
                           "┃        ┃     │  ├─ Binop -- op:'!='\n"
                           "┃        ┃     │  │  ├─ ProcCall\n"
                           "┃        ┃     │  │  │  ├─ Var -- name:'@fun_sideeffect'\n"
                           "┃        ┃     │  │  │  └─ NULL\n"
                           "┃        ┃     │  │  └─ Float -- val:'0.000000'\n"
                           "┃        ┃     │  ├─ Bool -- val:'1'\n"
                           "┃        ┃     │  └─ Bool -- val:'0'\n"
                           "┃        ┃     ┢─ Statements\n"
                           "┃        ┃     ┃  └─ ProcCall\n"
                           "┃        ┃     ┃     ├─ Var -- name:'@fun_increase_sideeffect'\n"
                           "┃        ┃     ┃     ┢─ Exprs\n"
                           "┃        ┃     ┃     ┃  └─ Int -- val:'2'\n"
                           "┃        ┃     ┃     ┗─ NULL\n"
                           "┃        ┃     ┡─ NULL\n"
                           "┃        ┃     └─ NULL\n"
                           "┃        ┣─ Statements\n"
                           "┃        ┃  └─ RetStatement\n"
                           "┃        ┃     └─ Int -- val:'0'\n"
                           "┃        ┗─ NULL\n"
                           "┣─ Declarations\n"
                           "┃  └─ FunDef -- has_export:'0'\n"
                           "┃     ├─ FunHeader -- type:'int'\n"
                           "┃     │  ├─ Var -- name:'@fun_no_sideeffect'\n"
                           "┃     │  └─ NULL\n"
                           "┃     └─ FunBody\n"
                           "┃        ┢─ VarDecs\n"
                           "┃        ┃  └─ VarDec -- type:'int'\n"
                           "┃        ┃     ├─ Var -- name:'@1_b'\n"
                           "┃        ┃     └─ NULL\n"
                           "┃        ┡─ NULL\n"
                           "┃        ├─ NULL\n"
                           "┃        ┢─ Statements\n"
                           "┃        ┃  └─ Assign\n"
                           "┃        ┃     ├─ Var -- name:'@1_b'\n"
                           "┃        ┃     └─ Int -- val:'15'\n"
                           "┃        ┣─ Statements\n"
                           "┃        ┃  └─ RetStatement\n"
                           "┃        ┃     └─ Binop -- op:'+'\n"
                           "┃        ┃        ├─ Int -- val:'1'\n"
                           "┃        ┃        └─ Var -- name:'@1_b'\n"
                           "┃        ┗─ NULL\n"
                           "┣─ Declarations\n"
                           "┃  └─ FunDef -- has_export:'0'\n"
                           "┃     ├─ FunHeader -- type:'float'\n"
                           "┃     │  ├─ Var -- name:'@fun_sideeffect'\n"
                           "┃     │  └─ NULL\n"
                           "┃     └─ FunBody\n"
                           "┃        ├─ NULL\n"
                           "┃        ├─ NULL\n"
                           "┃        ┢─ Statements\n"
                           "┃        ┃  └─ Assign\n"
                           "┃        ┃     ├─ Var -- name:'@0_used_global'\n"
                           "┃        ┃     └─ Float -- val:'10.000000'\n"
                           "┃        ┣─ Statements\n"
                           "┃        ┃  └─ RetStatement\n"
                           "┃        ┃     └─ Float -- val:'36.000000'\n"
                           "┃        ┗─ NULL\n"
                           "┣─ Declarations\n"
                           "┃  └─ FunDef -- has_export:'0'\n"
                           "┃     ├─ FunHeader -- type:'bool'\n"
                           "┃     │  ├─ Var -- name:'@fun_increase_sideeffect'\n"
                           "┃     │  ┢─ Params -- type:'int'\n"
                           "┃     │  ┃  └─ Var -- name:'@1_a'\n"
                           "┃     │  ┗─ NULL\n"
                           "┃     └─ FunBody\n"
                           "┃        ├─ NULL\n"
                           "┃        ├─ NULL\n"
                           "┃        ┢─ Statements\n"
                           "┃        ┃  └─ Assign\n"
                           "┃        ┃     ├─ Var -- name:'@0_i'\n"
                           "┃        ┃     └─ Binop -- op:'+'\n"
                           "┃        ┃        ├─ Var -- name:'@0_i'\n"
                           "┃        ┃        └─ Int -- val:'1'\n"
                           "┃        ┣─ Statements\n"
                           "┃        ┃  └─ RetStatement\n"
                           "┃        ┃     └─ Binop -- op:'<='\n"
                           "┃        ┃        ├─ Var -- name:'@0_i'\n"
                           "┃        ┃        └─ Var -- name:'@1_a'\n"
                           "┃        ┗─ NULL\n"
                           "┣─ Declarations\n"
                           "┃  └─ FunDef -- has_export:'1'\n"
                           "┃     ├─ FunHeader -- type:'void'\n"
                           "┃     │  ├─ Var -- name:'__init'\n"
                           "┃     │  └─ NULL\n"
                           "┃     └─ FunBody\n"
                           "┃        ├─ NULL\n"
                           "┃        ├─ NULL\n"
                           "┃        ┢─ Statements\n"
                           "┃        ┃  └─ ProcCall\n"
                           "┃        ┃     ├─ Var -- name:'@fun_extern_sideeffect'\n"
                           "┃        ┃     └─ NULL\n"
                           "┃        ┣─ Statements\n"
                           "┃        ┃  └─ Assign\n"
                           "┃        ┃     ├─ Var -- name:'@0_i'\n"
                           "┃        ┃     └─ Int -- val:'0'\n"
                           "┃        ┣─ Statements\n"
                           "┃        ┃  └─ Assign\n"
                           "┃        ┃     ├─ Var -- name:'@0_unused_exported'\n"
                           "┃        ┃     └─ Bool -- val:'1'\n"
                           "┃        ┗─ NULL\n"
                           "┗─ NULL\n";

    ASSERT_MLSTREQ(expected, root_string);

    expected =
        "┌─ 0: Program\n"
        "├─ __init: FunHeader -- type:'void' -- Params: (null)\n"
        "├─ @0_i: VarDec -- type:'int'\n"
        "├─ @fun_test: FunHeader -- type:'int' -- Params: (null)\n"
        "├─ @0_unused_exported: VarDec -- type:'bool'\n"
        "├─ @fun_extern_sideeffect: FunHeader -- type:'int' -- Params: (null)\n"
        "├─ @fun_sideeffect: FunHeader -- type:'float' -- Params: (null)\n"
        "├─ @fun_printInt: FunHeader -- type:'int' -- Params: int (Var -- name:'@0_val')\n"
        "├─ @fun_printNewlines: FunHeader -- type:'void' -- Params: int (Var -- name:'@0_val')\n"
        "├─ @fun_main: FunHeader -- type:'int' -- Params: (null)\n"
        "├─ @0_used_global: VarDec -- type:'float'\n"
        "├─ @fun_no_sideeffect: FunHeader -- type:'int' -- Params: (null)\n"
        "├─ @fun_increase_sideeffect: FunHeader -- type:'bool' -- Params: int (Var -- "
        "name:'@1_a')\n"
        "└────────────────────\n"
        "\n"
        "┌─ 1: FunDef '@fun_test' -- parent: '0: Program'\n"
        "├─ @1_a: VarDec -- type:'int'\n"
        "└────────────────────\n"
        "\n"
        "┌─ 1: FunDef '@fun_main' -- parent: '0: Program'\n"
        "├─ @for3_i: VarDec -- type:'int'\n"
        "├─ @1_a: VarDec -- type:'int'\n"
        "├─ @1_b: VarDec -- type:'int'\n"
        "├─ @1_k: VarDec -- type:'int'\n"
        "└────────────────────\n"
        "\n"
        "┌─ 1: FunDef '@fun_no_sideeffect' -- parent: '0: Program'\n"
        "├─ @1_b: VarDec -- type:'int'\n"
        "└────────────────────\n"
        "\n"
        "┌─ 1: FunDef '@fun_sideeffect' -- parent: '0: Program'\n"
        "└────────────────────\n"
        "\n"
        "┌─ 1: FunDef '@fun_increase_sideeffect' -- parent: '0: Program'\n"
        "├─ @1_a: Params -- type:'int'\n"
        "└────────────────────\n"
        "\n"
        "┌─ 1: FunDef '__init' -- parent: '0: Program'\n"
        "└────────────────────\n";

    ASSERT_MLSTREQ(expected, symbols_string);
}

TEST_F(OptimizationTest, DeadCodeElimination_WhileLoops)
{
    SetUpOpt("codegen/while_loops/main.cvc", Opt::DEADCODEELIMINATION);
    ASSERT_NE(nullptr, root);

    const char *expected = "Program\n"
                           "┢─ Declarations\n"
                           "┃  └─ FunDef -- has_export:'1'\n"
                           "┃     ├─ FunHeader -- type:'int'\n"
                           "┃     │  ├─ Var -- name:'@fun_main'\n"
                           "┃     │  └─ NULL\n"
                           "┃     └─ FunBody\n"
                           "┃        ├─ NULL\n"
                           "┃        ├─ NULL\n"
                           "┃        ┢─ Statements\n"
                           "┃        ┃  └─ RetStatement\n"
                           "┃        ┃     └─ Int -- val:'0'\n"
                           "┃        ┗─ NULL\n"
                           "┗─ NULL\n";

    ASSERT_MLSTREQ(expected, root_string);

    expected = "┌─ 0: Program\n"
               "├─ @fun_main: FunHeader -- type:'int' -- Params: (null)\n"
               "└────────────────────\n"
               "\n"
               "┌─ 1: FunDef '@fun_main' -- parent: '0: Program'\n"
               "└────────────────────\n";

    ASSERT_MLSTREQ(expected, symbols_string);
}

// /////////////////////////
// COMPILATION FAILURE tests
// /////////////////////////

// TEST_F(OptimizationTest, DoubleArrParams)
// {
//     SetUpNoExecute("milestone_8/double_arr_params/main.cvc");
//     ASSERT_EXIT(
//         run_code_gen_preparation(input_filepath.c_str()), testing::ExitedWithCode(1),
//         testing::AllOf(testing::HasSubstr("already defined"), testing::HasSubstr("3 Error")));
// }
